# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LevlUp
email: mitch@levlup.co
description: > # this means to ignore newlines until "baseurl:"
  LevlUp offers Infrastructure consulting and Development. LevlUp your business today!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://levlup.co" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_link: https://twitter.com/LevlUpCo
github_link:  https://github.com/LevlUp
facebook_link: 
linkedin_link: https://www.linkedin.com/in/mitchell-ogden-26475060
dribble_link: 

# Address information
address_street: 3251 Nina Rd
address_city: Gaylord
address_state: MI
address_zip: 49735

# Build settings
markdown: kramdown