# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LevlUp
email: mitch@levlup.co
description: > # this means to ignore newlines until "baseurl:"
  Infrastructure Consulting - Web Development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://levlup.co" # the base hostname & protocol for your site
logo: "/img/levlup.png"

# Social media profiles - feel free to add more here
twitter_username: levlupco
github_username:  levlup
facebook_username: 

# Address information
address_street: 3251 Nina Rd
address_city: Gaylord
address_state: MI
address_zip: 49735

# Build settings
markdown: kramdown
